### PR TITLE
Added a ``package.json`` to publish the module.

### PR DESCRIPTION
**Pull request by ehgoodenough**
## Purpose ##

Publish this SDK to NPM so we can consume your API. :]

https://docs.npmjs.com/getting-started/publishing-npm-packages

## Selfie ##

selfie-1

### CODE REVIEW

**Comment by ehgoodenough** [comment]
Oh, and sorry; I do already have a t-shirt from pitching yesterday; I didn't understand what you were asking earlier. Sorry!! :<

**Comment by ehgoodenough** [comment]
@MarcoWilliamsPF, it is done! Thanks for bringing that to my attention. :]

**Comment by MarcoWilliamsPF** [comment]
LGTM

**Comment by MarcoWilliamsPF** [comment]
made some new changes to the package.json and published.
https://www.npmjs.com/package/playfab-sdk

**Pull request merged**
